# Generated by Django 5.0.3 on 2024-03-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_jp', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Support', 'Support'), ('Fighter', 'Fighter'), ('Tank', 'Tank'), ('Assassin', 'Assassin'), ('Mage', 'Mage'), ('Marksman', 'Marksman')], max_length=20)),
                ('image_url', models.URLField()),
                ('article_url', models.URLField()),
            ],
        ),
    ]
