# Generated by Django 5.0.3 on 2024-04-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_herometadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='name_en',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name_jp',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
